### ISSUE TITLE
Not able to add custom redux store 

### ISSUE THREAD

**Issue by swarnimsuman** [twilio/flex-ui-sample#12] opened 2019-05-26 21:22 UTC
I'm trying to use twilio flex  in my application, but every time i tries to logout and login to my application whole redux store crashes with error:
                       TypeError: Cannot read property 'getState' of null

With new release we can add custom store for flex, and since i'm using typescript in my application it is failing with the error: 
 
```
Type 'Reducer<AppState>' is not assignable to type 'Reducer<AppState, AnyAction>'.
  Types of parameters 'state' and 'state' are incompatible.
    Type 'AppState | undefined' is not assignable to type 'AppState'.
      Type 'undefined' is not assignable to type 'AppState'.ts(2322)
rootReducer.tsx(45, 3): The expected type comes from property 'flex' which is declared here on type 'ReducersMapObject<{ flex: AppState; }, AnyAction>'
```

**Comment by tomsabin** [comment] 2019-06-26 08:29
I didn't have exactly the same issue as you but instead I was receiving this error when loading the webpage for the first time:

```
Failed to initialize Flex Invariant Violation: Could not find "store" in either the context or props of "Connect(t)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(t)".
```

This is caused by using a version of react-redux that is >v6.0.0 which [introduces a breaking change](https://github.com/reduxjs/react-redux/releases/tag/v6.0.0) with the `store` prop. I had previously installed the packages with `npm install redux react-redux --save` which installed react-redux v7.1.0.

This was resolved by installing react-redux v5.1.1 instead.

For visibility, here's the `App.js`, `index.js` and `package.json` files: https://gist.github.com/tomsabin/23b689a1293a73d97ba74361462db255

**Comment by AdrianaPineda** [comment] 2019-08-01 12:46
Hey @swarnimsuman, @tomsabin is correct. Can you make sure you are using react-redux version  `^5.0.6`?

**Closed by AdrianaPineda** 2019-08-01 12:46 UTC
Labels: question

**Comment by MiniMarker** [comment] 2019-10-22 14:38
This is still an issue, any updates to this?
